name: Build and test dcc - Darwin

on:
  push:

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Prepare test - get packages
      run: |
        pip3 install -q -r requirements.txt
        brew install llvm flex bison llvm
        echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
        echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH

    - name: Make dcc
      run: scons dcc

    - name: Test dcc
      run: scons test
