name: Compile the compiler

on:
  push:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Prepare test - get packages
      run: |
        python3 -m pip install --upgrade pip
        pip3 install --upgrade toml
        sudo apt install -y -q gcc-multilib
    
    - uses: actions/checkout@v2
    - name: Make dcc
      run: make -j$(nproc) all

    - name: Test dcc
      run: make test
