name: Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Get pip packages
      run: |
        python3 -m pip install --upgrade pip
        pip3 install --upgrade toml
    - uses: actions/checkout@v2
    - name: Test dcc
      run: ./test/dtest.py
